{{- if .Values.certificate.enabled -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "grafana.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ template "grafana.name" . }}-tls
  issuerRef:
    name: certificate-issuer
    kind: Issuer
  commonName: {{ .Values.certificate.domain }}
  dnsNames:
  - {{ .Values.certificate.domain }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - {{ .Values.certificate.domain }}
{{- end }}