apiVersion: v1
name: grafana
version: 2.3.9
appVersion: 6.0.0
kubeVersion: "^1.8.0-0"
description: Stacc Flow custom grafana chart
home: https://grafana.net
icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
sources:
  - https://bitbucket.org/stacc-flow/flow-infrastructure
maintainers:
  - name: Kristoffer-Andre Kalliainen
    email: kristoffer-andre.kalliainen@stacc.com
engine: gotpl
