---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    flux.weave.works/automated: 'true'
    flux.weave.works/tag.chart-image: glob:6.*
spec:
  releaseName: grafana
  chart:
    git: git@github.com:181192/gitops-multicluster-template
    path: charts/grafana
    ref: master
  values:
    image:
      repository: grafana/grafana
      tag: 6.2.0-beta1
    adminUser: admin
    adminPassword: Txc2f8Q4jtTRsdfsfhcZTGW4
    mysql:
      enabled: false
      passwordSecret: mysql
    ingress:
      enabled: false
    istio:
      enabled: true
      hostName: "*"
    persistence:
      enabled: false
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'istio'
          orgId: 1
          folder: 'Istio'
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/istio
        - name: 'kubernetes'
          orgId: 1
          folder: 'Kubernetes'
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/kubernetes
    dashboards:
      istio:
        galley-dashboard:
          file: dashboards/istio/galley-dashboard.json
        istio-mesh-dashboard:
          file: dashboards/istio/istio-mesh-dashboard.json
        istio-performance-dashboard:
          file: dashboards/istio/istio-performance-dashboard.json
        istio-service-dashboard:
          file: dashboards/istio/istio-service-dashboard.json
        istio-workload-dashboard:
          file: dashboards/istio/istio-workload-dashboard.json
        mixer-dashboard:
          file: dashboards/istio/mixer-dashboard.json
        pilot-dashboard:
          file: dashboards/istio/pilot-dashboard.json
      kubernetes:
        capacity-planning-dashboard:
          file: dashboards/kubernetes/capacity-planning-dashboard.json
        cluster-health-dashboard:
          file: dashboards/kubernetes/cluster-health-dashboard.json
        cluster-status-dashboard:
          file: dashboards/kubernetes/cluster-status-dashboard.json
        control-plane-status-dashboard:
          file: dashboards/kubernetes/control-plane-status-dashboard.json
        deployments-dashboard:
          file: dashboards/kubernetes/deployments-dashboard.json
        pods-dashboard:
          file: dashboards/kubernetes/pods-dashboard.json
        resource-requests-dashboard:
          file: dashboards/kubernetes/resource-requests-dashboard.json
        statefulsets-dashboard:
          file: dashboards/kubernetes/statefulsets-dashboard.json